-- Seed data for testing and development (PostgreSQL)
-- Password for all test accounts: password123
-- Hash generated with bcrypt cost 12

-- Volunteers
INSERT INTO volunteers (cc, username, email, pass, nome, apelido, nascimento, conducao, verificado, image_path, biografia, genero, interesses, pop_alvo, disponibilidade, concelho, distrito, freguesia, telemovel) VALUES
('12345678', 'joao_silva',       'joao.silva@example.com',       '$2a$12$v4WCuNUKf3KHi7amldcaTeT3NR/mnxQmREtezJ2OkHJq/6xG77K8y', 'João',      'Silva',     '1995-05-15', TRUE,  TRUE, '/assets/Imagens/perfilDefault.png', 'Apaixonado por ajudar a comunidade e fazer a diferença na vida das pessoas.',        'M', 'Ajuda a idosos, Distribuição de alimentos, Apoio escolar', 'Idosos, Crianças',      'Fins de semana e feriados',     'Lisboa',    'Lisboa',   'Alvalade',        '912000001'),
('87654321', 'maria_santos',     'maria.santos@example.com',     '$2a$12$v4WCuNUKf3KHi7amldcaTeT3NR/mnxQmREtezJ2OkHJq/6xG77K8y', 'Maria',     'Santos',    '1992-08-22', TRUE,  TRUE, '/assets/Imagens/perfilDefault.png', 'Voluntária há 5 anos, especializada em ações sociais e ambientais.',                'F', 'Meio ambiente, Apoio social, Eventos culturais',             'Famílias, Jovens',      'Tardes durante a semana',       'Porto',     'Porto',    'Cedofeita',       '912000002'),
('11223344', 'carlos_oliveira',  'carlos.oliveira@example.com',  '$2a$12$v4WCuNUKf3KHi7amldcaTeT3NR/mnxQmREtezJ2OkHJq/6xG77K8y', 'Carlos',    'Oliveira',  '1988-12-03', FALSE, TRUE, '/assets/Imagens/perfilDefault.png', 'Engenheiro que dedica tempo livre a projetos de voluntariado técnico.',              'M', 'Tecnologia, Ensino, Manutenção',                             'Jovens, Adultos',       'Noites e fins de semana',       'Coimbra',   'Coimbra',  'Sé Nova',         '912000003'),
('22334455', 'ana_ferreira',     'ana.ferreira@example.com',     '$2a$12$v4WCuNUKf3KHi7amldcaTeT3NR/mnxQmREtezJ2OkHJq/6xG77K8y', 'Ana',       'Ferreira',  '1997-03-10', FALSE, TRUE, '/assets/Imagens/perfilDefault.png', 'Estudante de medicina com paixão pelo apoio a populações vulneráveis.',              'F', 'Saúde, Apoio a idosos, Primeiros socorros',                  'Idosos, Sem-abrigo',    'Manhãs e fins de semana',       'Braga',     'Braga',    'São Vítor',       '912000004'),
('33445566', 'pedro_costa',      'pedro.costa@example.com',      '$2a$12$v4WCuNUKf3KHi7amldcaTeT3NR/mnxQmREtezJ2OkHJq/6xG77K8y', 'Pedro',     'Costa',     '1990-07-19', TRUE,  TRUE, '/assets/Imagens/perfilDefault.png', 'Empresário que acredita que a responsabilidade social começa em cada um de nós.',    'M', 'Empreendedorismo social, Formação profissional',             'Jovens desempregados',  'Fins de semana',                'Faro',      'Faro',     'Faro (Sé)',        '912000005'),
('44556677', 'sofia_mendes',     'sofia.mendes@example.com',     '$2a$12$v4WCuNUKf3KHi7amldcaTeT3NR/mnxQmREtezJ2OkHJq/6xG77K8y', 'Sofia',     'Mendes',    '2000-01-25', FALSE, TRUE, '/assets/Imagens/perfilDefault.png', 'Recém-licenciada em psicologia, motivada a apoiar a saúde mental da comunidade.',    'F', 'Saúde mental, Apoio emocional, Grupos de jovens',            'Jovens, Adultos',       'Tardes e noites',               'Setúbal',   'Setúbal',  'Setúbal (São Julião)', '912000006'),
('55667788', 'rui_almeida',      'rui.almeida@example.com',      '$2a$12$v4WCuNUKf3KHi7amldcaTeT3NR/mnxQmREtezJ2OkHJq/6xG77K8y', 'Rui',       'Almeida',   '1985-09-14', TRUE,  TRUE, '/assets/Imagens/perfilDefault.png', 'Professor aposentado que quer continuar a contribuir para a educação da sociedade.',  'M', 'Educação, Tutoria, Literacia digital',                       'Crianças, Idosos',      'Manhãs de segunda a sexta',     'Évora',     'Évora',    'Évora (Sé)',       '912000007'),
('66778899', 'inês_rodrigues',   'ines.rodrigues@example.com',   '$2a$12$v4WCuNUKf3KHi7amldcaTeT3NR/mnxQmREtezJ2OkHJq/6xG77K8y', 'Inês',      'Rodrigues', '1993-11-08', FALSE, FALSE,'/assets/Imagens/perfilDefault.png', 'Nutricionista que quer ajudar famílias carenciadas a ter uma alimentação saudável.', 'F', 'Nutrição, Distribuição alimentar, Workshops de culinária',   'Famílias, Crianças',    'Fins de semana',                'Aveiro',    'Aveiro',   'Aveiro',          '912000008'),
('77889900', 'miguel_lopes',     'miguel_lopes@example.com',     '$2a$12$v4WCuNUKf3KHi7amldcaTeT3NR/mnxQmREtezJ2OkHJq/6xG77K8y', 'Miguel',    'Lopes',     '1999-06-30', TRUE,  TRUE, '/assets/Imagens/perfilDefault.png', 'Estudante de arquitetura com interesse em projetos de habitação social.',             'M', 'Habitação social, Reabilitação urbana, Apoio comunitário',   'Famílias carenciadas',  'Fins de semana e feriados',     'Viseu',     'Viseu',    'Viseu',           '912000009'),
('88990011', 'catarina_nunes',   'catarina_nunes@example.com',   '$2a$12$v4WCuNUKf3KHi7amldcaTeT3NR/mnxQmREtezJ2OkHJq/6xG77K8y', 'Catarina',  'Nunes',     '1996-04-17', FALSE, TRUE, '/assets/Imagens/perfilDefault.png', 'Assistente social que quer fazer mais além do horário de trabalho.',                 'F', 'Apoio social, Acompanhamento familiar, Inclusão social',     'Idosos, Famílias',      'Tardes de segunda a sexta',     'Guimarães', 'Braga',    'Guimarães (Oliveira, São Paio)', '912000010');

-- Institutions
INSERT INTO institutions (nome, nome_representante, email_representante, email, pass, telefone, morada, concelho, distrito, freguesia, descricao, tipo, verificado, image_path) VALUES
('Cruz Vermelha Portuguesa',            'Ana Costa',         'ana.costa@cruzvermelha.pt',          'contacto@cruzvermelha.pt',      '$2a$12$v4WCuNUKf3KHi7amldcaTeT3NR/mnxQmREtezJ2OkHJq/6xG77K8y', '213913600', 'Jardim 9 de Abril, 1-5, 1249-083 Lisboa',        'Lisboa',    'Lisboa',  'Misericórdia',      'Organização humanitária que presta auxílio a pessoas em situação de vulnerabilidade social.',         'Organização Humanitária',   TRUE, '/assets/Imagens/perfilDefault.png'),
('Refood',                              'Pedro Martins',     'pedro.martins@refood.pt',            'info@refood.pt',                '$2a$12$v4WCuNUKf3KHi7amldcaTeT3NR/mnxQmREtezJ2OkHJq/6xG77K8y', '912345678', 'Rua da Prata, 80, 1100-420 Lisboa',               'Lisboa',    'Lisboa',  'Santa Maria Maior', 'Movimento cívico que combate o desperdício alimentar através da redistribuição de excedentes.',       'ONG Ambiental/Social',      TRUE, '/assets/Imagens/perfilDefault.png'),
('Banco Alimentar Contra a Fome',       'Sofia Rodrigues',   'sofia.rodrigues@bancoalimentar.pt',  'geral@bancoalimentar.pt',       '$2a$12$v4WCuNUKf3KHi7amldcaTeT3NR/mnxQmREtezJ2OkHJq/6xG77K8y', '217941200', 'Rua de São Bento, 640, 1250-222 Lisboa',          'Lisboa',    'Lisboa',  'São Bento',         'Instituição de solidariedade social que luta contra o desperdício alimentar e a fome.',              'Instituição de Solidariedade', TRUE, '/assets/Imagens/perfilDefault.png'),
('AMI - Assistência Médica Internacional','Luís Fonseca',    'luis.fonseca@ami.org.pt',            'ami@ami.org.pt',                '$2a$12$v4WCuNUKf3KHi7amldcaTeT3NR/mnxQmREtezJ2OkHJq/6xG77K8y', '213969510', 'Rua José do Patrocínio, 49, 1959-003 Lisboa',    'Lisboa',    'Lisboa',  'Marvila',           'ONG humanitária que atua em zonas de conflito e populações vulneráveis em Portugal e no mundo.',     'ONG Humanitária',           TRUE, '/assets/Imagens/perfilDefault.png'),
('Cáritas Portuguesa',                  'Marta Vieira',      'marta.vieira@caritas.pt',            'caritas@caritas.pt',            '$2a$12$v4WCuNUKf3KHi7amldcaTeT3NR/mnxQmREtezJ2OkHJq/6xG77K8y', '213460585', 'Rua Afonso de Albuquerque, 6, 1350-003 Lisboa',  'Lisboa',    'Lisboa',  'Campo de Ourique',  'Organização da Igreja Católica que promove o desenvolvimento humano e a solidariedade social.',      'Organização Religiosa/Social', TRUE, '/assets/Imagens/perfilDefault.png'),
('SOS Aldeia Solidária do Porto',       'Ricardo Pinto',     'ricardo.pinto@aldeia-porto.pt',      'info@aldeia-porto.pt',          '$2a$12$v4WCuNUKf3KHi7amldcaTeT3NR/mnxQmREtezJ2OkHJq/6xG77K8y', '225508900', 'Av. da Boavista, 1234, 4100-130 Porto',          'Porto',     'Porto',   'Lordelo do Ouro',   'Associação de apoio a famílias carenciadas e crianças em risco no Grande Porto.',                   'Associação de Solidariedade', TRUE, '/assets/Imagens/perfilDefault.png'),
('APPACDM Braga',                       'Teresa Azevedo',    'teresa.azevedo@appacdm-braga.pt',    'appacdm@appacdm-braga.pt',      '$2a$12$v4WCuNUKf3KHi7amldcaTeT3NR/mnxQmREtezJ2OkHJq/6xG77K8y', '253218190', 'Av. Central, 100, 4710-228 Braga',               'Braga',     'Braga',   'Braga (São José de São Lázaro)', 'Associação que promove a inclusão social de pessoas com deficiência intelectual.',                  'Associação de Apoio Social', TRUE, '/assets/Imagens/perfilDefault.png');
